name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt

      # Frontend steps would go here, for now, placeholder
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          pytest --cov=.

      # Add frontend tests here as needed
